services:
  backend:
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://pfa-db:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC
    networks:
      - default
      - proxy
      - pfa-db-net
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy 
      - traefik.http.routers.pfa-api.rule=Host(`api.adoptpetsforall.com`)
      - traefik.http.routers.pfa-api.entrypoints=websecure
      - traefik.http.routers.pfa-api.tls=true
      - traefik.http.routers.pfa-api.tls.certresolver=le
      - traefik.http.services.pfa-api.loadbalancer.server.port=8080

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: https://api.adoptpetsforall.com
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.pfa-web.rule=Host(`adoptpetsforall.com`,`www.adoptpetsforall.com`)
      - traefik.http.routers.pfa-web.entrypoints=websecure
      - traefik.http.routers.pfa-web.tls=true
      - traefik.http.routers.pfa-web.tls.certresolver=le
      - traefik.http.services.pfa-web.loadbalancer.server.port=80

networks:
  proxy:
    external: true
  pfa-db-net:
    external: true

