# mySQL configuration (prod)
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
db.name=${DB_NAME}

spring.datasource.hikari.data-source-properties.allowPublicKeyRetrieval=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true
