spring.application.name=pfa

# keep base config "environment-agnostic"
spring.jpa.show-sql=true
spring.flyway.repair-on-migrate=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
